### ISSUE TITLE
Problem getting HASSIO_VERSION variable in ubuntu 18.04

### ISSUE THREAD

**Issue by orensbruli** [Kanga-Who/home-assistant#10]
This is the execution on ubuntu 18.04 with bash -x
```
+ case $ARCH in
+ MACHINE=qemux86-64
+ HASSIO_DOCKER=homeassistant/amd64-hassio-supervisor
+ [[ ! qemux86-64 =~ ^(intel-nuc|odroid-c2|odroid-n2|odroid-xu|qemuarm|qemuarm-64|qemux86|qemux86-64|raspberrypi|raspberrypi2|raspberrypi3|raspberrypi4|raspberrypi3-64|raspberrypi4-64|tinker)$ ]]
+ '[' '!' -d /usr/share/hassio ']'
++ curl -s https://version.home-assistant.io/stable.json
++ jq -e -r .supervisor
+ HASSIO_VERSION=
+ cat
+ info 'Install supervisor Docker container'
+ echo -e '\e[32m[info] Install supervisor Docker container\e[39m'
[info] Install supervisor Docker container
+ docker pull homeassistant/amd64-hassio-supervisor:
invalid reference format
```

Any idea why this could be happening?

Edit: If I execute just this, its working:
```
robolab@robolab-server:~$ curl -s https://version.home-assistant.io/stable.json | jq -e -r .supervisor
249
```

**Comment by ahmadnbl** [comment]
just got the same problem and figured-out why

@orensbruli do you use wifi connection and previously use `ifup`/`ifdown` or setting it up in `/etc/network/interfaces` before running this command?

if so, before running that `supervised-installer.sh` script, you should setup your machine connection using the `NetworkManager` itself.

for me, because I previously using the `ifup`/`ifdown` method to configure the wifi radio connection, it conflicted with `Network-Manager`

**Comment by chabala** [comment]
Seems foolish for the install script to be messing with the network interfaces immediately prior to using curl to check some URL for a version.
But then it also seems foolish for it to be messing with the network interfaces at all. The script doesn't even check if it needs to make changes before replacing the interface config outright.
I'm just going to comment out some of this foolishness locally ...

**Comment by Kanga-Who** [comment]
> 
> 
> Seems foolish for the install script to be messing with the network interfaces immediately prior to using curl to check some URL for a version.
> But then it also seems foolish for it to be messing with the network interfaces at all. The script doesn't even check if it needs to make changes before replacing the interface config outright.
> I'm just going to comment out some of this foolishness locally ...

Do you have something useful to contribute, or did you just come to complain? If you don't have a PR to improve the code, then keep your opinions of what may or may not be foolish to yourself.

**Comment by chabala** [comment]
I'm good, looks like a PR is already in progress upstream https://github.com/home-assistant/supervised-installer/pull/142
