### ISSUE TITLE
Issue with Installing Portainer

### ISSUE THREAD

**Issue by instinxx** [Kanga-Who/home-assistant#13]
After following the excellent instructions here:
https://community.home-assistant.io/t/installing-home-assistant-using-proxmox/201835

I proceeded to:
https://github.com/Kanga-Who/home-assistant/blob/53ac6a3e77e3654a4f5835bde7cef91493cc08a0/Install%20Samba%2C%20Portainer%20and%20MQTT.md

When attempting to run:
`sudo docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer`
I get an error saying
`sudo: docker: command not found`

Is it possible that a docker dependency is not getting installed with the original instructions? I do not know much about docker but would be happy to troubleshoot with some direction.

**Comment by ma3d1um** [comment]
I was struggling with this too, but I discovered that Kanga-Who's setup has Portainer/MQTT/Samba etc on the other Ubuntu VM:
https://community.home-assistant.io/t/installing-home-assistant-using-proxmox/201835/88?u=maedium
