### ISSUE TITLE
invalid reference format

### ISSUE THREAD

**Issue by jbrepogmailcom** [Kanga-Who/home-assistant#16]
What can I do with this?

```
[info] Do you want to proceed with overwriting the /etc/network/interfaces file? [N/y] 
y
[info] Replacing /etc/network/interfaces
[info] Restarting NetworkManager
[info] Install supervisor Docker container
invalid reference format
```

**Comment by AlexHeylin** [comment]
I got this too on Debian 10.9.0 AMD64 while following these instructions https://github.com/Kanga-Who/home-assistant/blob/master/Supervised%20Install%20on%20Debian.md 

I had already set a static IP in /etc/network/interfaces and chose No, to not overwrite the /etc/network/interfaces and lose my static IP. As far as I can see from the code, if I'd said Yes my static IP would have been lost which isn't great when connected via ssh (without local access to the machine).

**Comment by Kanga-Who** [comment]
If you choose to run a Supervised installation, HA wants to run (almost) all aspects of the OS, including network config. Something you have to deal with.
