### ISSUE TITLE
Add support for .zip in Proxmox installation

### ISSUE THREAD

**Issue by PaoloTK** [Kanga-Who/home-assistant#24]
I tried following the "Home Assistant with Proxmox installation" guide but the install script was failing with the following error:

`[ERROR] 0@115 Unable to handle file extension 'zip'.`

I downloaded the script and added a third option in the script to handle .zip files:

    # Extract Home Assistant disk image
    msg "Extracting disk image..."
    case $FILE in
      *"gz") gunzip -f $FILE;;
      *"xz") xz -d $FILE;;
      *"zip") unzip $FILE;;
      *) die "Unable to handle file extension '${FILE##*.}'.";;
    esac

The script executed correctly and the VM is up and running.

**Comment by Kanga-Who** [comment]
There is already a check for `.zip` files added into the script to cover this.
```
# Check for and Install unzip (if needed)
if [[ $FILE == *.zip ]]; then
  msg "Checking for unzip command"
  if ! command -v unzip &> /dev/null; then
    msg "unzip not found, installing..."
    apt install unzip -y
  fi
fi
```

Are you saying that with this the script did not work?

**Comment by Kanga-Who** [comment]
I've just tested the script as is on my Proxmox machine and it works without issue. See below.
```
root@proxmox:~# bash -c "$(wget -qLO - https://raw.githubusercontent.com/Kanga-Who/home-assistant/master/hassos_install.sh)"
[INFO] Using 'local-lvm' for storage location.
[INFO] Container ID is 103.
Getting URL for latest Home Assistant disk image...
Downloading disk image...
Checking for unzip command
unzip not found, installing...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  zip
The following NEW packages will be installed:
  unzip
0 upgraded, 1 newly installed, 0 to remove and 27 not upgraded.
Need to get 172 kB of archives.
After this operation, 580 kB of additional disk space will be used.
Get:1 http://ftp.debian.org/debian buster/main amd64 unzip amd64 6.0-23+deb10u2 [172 kB]
Fetched 172 kB in 0s (2,220 kB/s)
Selecting previously unselected package unzip.
(Reading database ... 71110 files and directories currently installed.)
Preparing to unpack .../unzip_6.0-23+deb10u2_amd64.deb ...
Unpacking unzip (6.0-23+deb10u2) ...
Setting up unzip (6.0-23+deb10u2) ...
Processing triggers for mime-support (3.62) ...
Processing triggers for man-db (2.8.5-2) ...
Extracting disk image...
Archive:  haos_ova-6.1.vmdk.zip
  inflating: haos_ova-6.1.vmdk       
Creating VM...
Adding serial port and configuring console...
[INFO] Completed Successfully! New VM ID is 103.
```

**Comment by PaoloTK** [comment]
> There is already a check for `.zip` files added into the script to cover this.
> 
> ```
> # Check for and Install unzip (if needed)
> if [[ $FILE == *.zip ]]; then
>   msg "Checking for unzip command"
>   if ! command -v unzip &> /dev/null; then
>     msg "unzip not found, installing..."
>     apt install unzip -y
>   fi
> fi
> ```
> 
> Are you saying that with this the script did not work?

Yes.

**Comment by Kanga-Who** [comment]
@PaoloTK as already stated...

> I've just tested the script as is on my Proxmox machine and it works without issue. See below.

**Comment by PaoloTK** [comment]
> @PaoloTK as already stated...
> 
> > I've just tested the script as is on my Proxmox machine and it works without issue. See below.

I'm glad it's working on your end, but it failed on my bog-standard Proxmox install. If you're not interested in figuring out what went wrong at least if anyone else gets the same error they have a way to get around it.

**Comment by Kanga-Who** [comment]
> If you're not interested in figuring out what went wrong

I have tested it on 2 different Proxmox installs/machines, and it works as it should. I would say that is completely the opposite of "not being interested in figuring out what went wrong."

If I can't find any problem on 2 different machines and no one has commented with the same issue on the HA forums in my guide thread, I'm not sure what else I can do.
