### ISSUE TITLE
Add hint how to enable apparmor in "Installing Home Assistant Supervised on Raspberry Pi OS"

### ISSUE THREAD

**Issue by kongo09** [Kanga-Who/home-assistant#25]
Supervisor expects AppArmor to be active. At least on the 64bit version of Pi OS this is not loaded at boot even though the kernel module is there.

Solution:
add `apparmor=1 security=apparmor` to `/boot/cmdline.txt`

**Comment by shyney7** [comment]
@kongo09 thx this helped me!

**Comment by Ridder90** [comment]
What if `/boot/cmdline.txt` does not exists? Thnx!

**Comment by snmcma** [comment]
This cmdline.txt file is located in the root directory, just add these commands to it

**Comment by HuckleberryLovesYou** [comment]
> What if `/boot/cmdline.txt` does not exists? Thnx!

It isn't located at `boot/cmdline.txt` anymore. Now it's located in the firmware folder under `/boot/firmware/cmdline.txt`

You might wanna look into my Repository about the installation [here](https://github.com/HuckleberryLovesYou/Homeassistant-Supervised-on-Raspberry-Pi-5)

**Comment by FlyWieEinAirplane** [comment]
In case someone needs this: in my installation, I found the `cmdline.txt` file below `/mnt/boot/`
