### ISSUE TITLE
daemon.json: No such file or directory

### ISSUE THREAD

**Issue by stamandr** [Kanga-Who/home-assistant#28]
I am receiving the following error. 

bash: line 74: /etc/docker/daemon.json: No such file or directory

root@HP6300:~# docker --version
Docker version 20.10.9, build c2ea9bc
root@HP6300:~# curl -sL "https://raw.githubusercontent.com/Kanga-Who/home-assistant/master/supervised-installer.sh" | bash -s
[info]
[info] This script is taken from the official
[info]
[info] Home Assistant Supervised script available at
[info]
[info] https://github.com/home-assistant/supervised-installer
[info]
[info] Creating default docker daemon configuration /etc/docker/daemon.json
bash: line 74: /etc/docker/daemon.json: No such file or directory

**Comment by hellresistor** [comment]
you missing full comand ... after bash ....

**Comment by stamandr** [comment]
This is directly from the instructions. Step 2.2

( https://github.com/Kanga-Who/home-assistant/blob/master/Supervised%20Install%20on%20Debian.md ) I did not miss anything in the command. 
curl -sL "https://raw.githubusercontent.com/Kanga-Who/home-assistant/master/supervised-installer.sh" | bash -s

**Comment by hellresistor** [comment]
Friend try remove all `< dev/null ` on all commands.

I have detect some problem related with this `CONFIG=$SYSCONFDIR/hassio.json`
Will return --/hassio.json

I am running on rpi4 aarch64 debian11

Give some feedback

**Comment by stamandr** [comment]
Like this ?

curl -sL "https://raw.githubusercontent.com/Kanga-Who/home-assistant/master/supervised-installer.sh" | bash -s remove all < dev/null

**Comment by hellresistor** [comment]
forget that

is some problem with ethtool .... "Autonegotiation" is unset ,, are show on console.

@Kanga-Who is something to upgrade on script?
on my  rpi4 starts a loop to get network 

![superviseddebian11rpi4](https://user-images.githubusercontent.com/50468493/138819362-e355ed4b-b9f2-4204-a503-1f3ed1dd0c0a.jpg)
