### ISSUE TITLE
broken installation

### ISSUE THREAD

**Issue by radoslavirha** [Kanga-Who/home-assistant#29]
Hi,

I tried to run new installation, but it seems https://github.com/home-assistant/supervised-installer changed some files location in this commit:

https://github.com/home-assistant/supervised-installer/commit/6003c366f94bbe9bd4226a0412efb25bb2e92e72

Can It be fixed?

Thanks

**Comment by radoslavirha** [comment]
It seems to be fixed if I change supervised-installer.sh

from

URL_RAW_BASE="https://raw.githubusercontent.com/home-assistant/supervised-installer/master/files"

to 
URL_RAW_BASE="https://raw.githubusercontent.com/home-assistant/supervised-installer/3717667ff1e544b9660d3a6ab7e9b29f8b33a049/files" (the latest commit before changes)

**Comment by ChrisKoh83** [comment]
Did an updated Version here: https://github.com/ChrisKoh83/home-assistant
