### ISSUE TITLE
env check for avahi-daemon fails without symlink

### ISSUE THREAD

**Issue by jonlt** [Kanga-Who/home-assistant#4]
After following you guide on the forum, your script failed on the `avahi-daemon` env check. I was able to "fix" it by adding a symlink from `/etc/init.d/avahi-daemon` to `/bin/avahi-daemon`

output from `lsb_release -a`:

    No LSB modules are available.
    Distributor ID:  Debian
    Description:     Debian GNU/Linux 10 (buster)
    Release:          10
    Codename:     buster

Maybe something to add to the guide, or the script.

Thank you very much for providing this script!

**Comment by Kanga-Who** [comment]
That's odd, the procedure was tested twice on 2 different machines using this exact guide. I'll test again tomorrow and see if I can replicate the error.

BTW, the script is not mine, I forked it from the (old) official Home Assistant Github.

**Comment by jonlt** [comment]
> I'll test again tomorrow and see if I can replicate the error.

Don't rush for my sake. I worked around it and moved on. Just wanted to let you know in case it was a common issue.
