### ISSUE TITLE
installer stopped working

### ISSUE THREAD

**Issue by ryrzy** [Kanga-Who/home-assistant#7]
hi, i found now that your installer stoped working, i found that there are some changes in home-assistant/supervised-installer  https://github.com/home-assistant/supervised-installer/commit/93c6cb330e5fefa30ae8f8cefea46a09adbba7ea#diff-2f94a8ab083008dc2cd1c1fe8aa07572

for example DOCKER_SERVICE to SERVICE_DOCKER 
etc :)

**Comment by Kanga-Who** [comment]
Cheers, have adjusted. Should work now. Thanks for letting me know.
