### ISSUE TITLE
Thank you for this! - Small Typon in script

### ISSUE THREAD

**Issue by Tollbringer** [Kanga-Who/home-assistant#8]
Thanks for sharing this.

I noticed a small typo right at the start of your supervised-install.sh. I have not ready the entire script yet, but if I happen to notice anything else I will come back and edit my issue, if you have not already closed it :).

" declare -a MISSING_**PACAKGES** "

Awesome work.

**Comment by Kanga-Who** [comment]
Thank you for the heads up, fixed.

**Comment by Tollbringer** [comment]
I suppose it's Karma that I typo'd in my post to tell you about your typo!!!

" Thank you for this! - Small **_Typon_** in script #8 "

LOL! :)
